### PR TITLE
Added SemaphoreCache to limit concurrency for certain expensive operations

### PR DESCRIPTION
**Pull request by fuxingloh**
#### What kind of PR is this?:

/kind chore

#### What this PR does / why we need it:

Certain operations such as #136 and #246 are expensive to compute, this will limit the concurrency of that critical zone to just 2 with double-checked locking.

This is a pre-req for #246.

### CODE REVIEW

**Comment by monstrobishi** [comment]
I did some reading on this recently, are we sending a `503 Retry-After` if the cache is empty but there is an ongoing calculation? Or is it able to block and return the cached result from the previous request.

**Comment by fuxingloh** [comment]
> I did some reading on this recently, are we sending a `503 Retry-After` if the cache is empty but there is an ongoing calculation? Or is it able to block and return the cached result from the previous request.

This will block (45 seconds) until it acquires a lock, then process. When the lock is acquired it will check cache again before fetching. For double-checked locking.

**Comment by fuxingloh** [comment]
> I did some reading on this recently, are we sending a `503 Retry-After` if the cache is empty but there is an ongoing calculation? Or is it able to block and return the cached result from the previous request.

This will block (45 seconds) until it acquires a lock, then process. When the lock is acquired it will check cache again before fetching. For double-checked locking.

**Review by monstrobishi — APPROVED** [review]
Thanks! According to `async-mutex` it will reject the promise in the case of a timeout, so in that case we could send a `503 Retry-After` to indicate to the client that they can try again after a set interval.

**Review by canonbrother — APPROVED** [review]

**Pull request merged**
