### PR TITLE
feat(api/swaps/aggregated): include USD value for aggregated swaps

### PR DESCRIPTION
**Pull request by fuxingloh**
#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

Resolve USD value of AggregatedSwap at current dex prices on controller.

For graphing on https://deploy-preview-1008--defi-scan.netlify.app/dex/5

### CODE REVIEW

**Review by ivan-zynesis — APPROVED** [review]
Looks good.

Just that history asset amount evaluations are with current USD rate sounds weird to me. (very subjective to context)

**Comment by joeldavidw** [comment]
> Looks good.
> 
> Just that history asset amount evaluations are with current USD rate sounds weird to me. (very subjective to context)

Yea same sentiments. This data is required for graphs on scan but with only the latest USD rate the graphs would be inaccurate.

**Comment by fuxingloh** [comment]
TBH, I follow the same sentiments as well. As dex event prices aren't streamed out in real-time from the node and there isn't a reliable way to capture those data for indexing. 

This is the best we could do (for now) but the best is just not enough as pointed out from the above 2 comments. Let's keep the PR as it is and see what else we could do.

**Comment by fuxingloh** [comment]
I am going to merge this in, but the consumers of this endpoint should use it sparingly...

**Comment by fuxingloh** [comment]
> I am going to merge this in, but the consumers of this endpoint should use it sparingly...

We will plan another API integration for historical dex prices, since we need that too

**Pull request merged**
