### PR TITLE
Index oracle price data

### LINKED ISSUE #144: `Oracles` Service/Controller
#### What would you like to be added:

After the completion of https://github.com/DeFiCh/jellyfish/issues/202 `rpc_oracles.cpp` we need OraclesController to be implemented on the whale side which is sanitized for modern development.

Very similar to Token & PoolPair Controller. You can expect to implement the controller in the same design pattern as the existing controllers. Your end consumer is the explorer and light wallet to display price in a graph.

/triage accepted
/assign @jingyi2811 
/priority important-soon

/area module-api

### PR DESCRIPTION
**Pull request by jingyi2811**
What kind of PR is this?:
/kind feature

What this PR does / why we need it:
Index oracle price data

Which issue(s) does this PR fixes?:
Fixes #144

Additional comments?:

### CODE REVIEW

**Comment by monstrobishi** [comment]
Can you quickly summarise what's the difference between OraclePriceFeed and OraclePriceData? it's not immediately obvious when reading the code. Perhaps some

**Comment by monstrobishi** [comment]
Perhaps the names can be changed so it's more clear

**Comment by jingyi2811** [comment]
Price Feed = APPL, TESL
Price Data = 0.5@APPL, 1.0@TESL

Do you have any better suggestions?

**Comment by jingyi2811** [comment]
Close this PR. I shall apply all the comments and suggestions to #201

**Pull request closed without merging**
