### PR TITLE
feat(controller): token swap pathfinding getallswappabletokens

### PR DESCRIPTION
**Pull request by eli-lim**
#### What kind of PR is this?:
/kind feature

#### What this PR does / why we need it:
- Implements `/poolpairs/paths/swappable/1` endpoint to retrieve all swappable tokens given a token
- To merge after #822 

Returns response:
`poolswap/paths/swappable/1`
```javascript
{
  fromToken: { id: '1', symbol: 'A' },
  swappableTokens: [
    { id: '7', symbol: 'G' },
    { id: '0', symbol: 'DFI' },
    { id: '24', symbol: 'USDT' },
    { id: '6', symbol: 'F' },
    { id: '5', symbol: 'E' },
    { id: '4', symbol: 'D' },
    { id: '3', symbol: 'C' },
    { id: '2', symbol: 'B' }
  ]
}
```

#### Which issue(s) does this PR fixes?:
Fixes part of #809

### CODE REVIEW

**Review by thedoublejay — CHANGES_REQUESTED** [review]
On the list of swappable token, can we exclude the "from" token on the list?

**Comment by fuxingloh** [comment]
Should implement `displaySymbol` for all `TokenIdentifier`, since the product team need that information to display the symbol correctly on the front.

e.g. https://github.com/DeFiCh/whale/pull/847

**Comment by fuxingloh** [comment]
> Should implement `displaySymbol` for all `TokenIdentifier`, since the product team need that information to display the symbol correctly on the front.
> 
> e.g. #847

@thedoublejay you need it right?

**Comment by thedoublejay** [comment]
> #847

Yep! We're using displaySymbol across the app

**Comment by eli-lim** [comment]
Included the displayName in all the responses @thedoublejay

**Review by fuxingloh — APPROVED** [review]

**Pull request merged**
